# Generated by Django 5.0.1 on 2024-01-15 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('performance_score', models.FloatField()),
                ('kpi_name', models.CharField(default='default_value', max_length=255)),
                ('metric', models.CharField(default='default_value', max_length=255)),
                ('fact', models.FloatField()),
                ('finished', models.FloatField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.employee')),
            ],
        ),
    ]
