# Generated by Django 5.0.1 on 2024-01-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='premium',
            field=models.FloatField(null=True),
        ),
    ]
