# Generated by Django 5.0.1 on 2024-02-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='table_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='kpi_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='method',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='metric',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='premium',
            field=models.TextField(),
        ),
    ]
