# Generated by Django 5.0.1 on 2024-02-08 13:34

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
