# Generated by Django 5.0.1 on 2024-03-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fixed',
            field=models.FloatField(null=True),
        ),
    ]
