# Generated by Django 5.0.1 on 2024-02-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='table_number',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
