# Generated by Django 5.0.1 on 2024-02-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0002_alter_kpi_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="month",
            field=models.DateField(),
        ),
    ]
