# Generated by Django 5.0.1 on 2024-02-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
