# Generated by Django 5.0.1 on 2024-03-15 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_kpi_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('performance_score', models.FloatField()),
                ('kpi_name', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=255)),
                ('fact', models.FloatField()),
                ('finished', models.FloatField(null=True)),
                ('premium', models.TextField()),
                ('definition', models.TextField()),
                ('method', models.TextField()),
                ('weight', models.FloatField(null=True)),
                ('activity', models.CharField(default='Нет', max_length=4)),
                ('overall', models.FloatField(null=True)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
