# Generated by Django 5.0.1 on 2024-04-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_kpi_month_alter_kpiarchive_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiarchive',
            name='month',
            field=models.DateField(auto_now_add=True),
        ),
    ]
