# Generated by Django 5.0.1 on 2024-01-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_kpi_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='definition',
            field=models.TextField(default='default_value'),
        ),
    ]
