# Generated by Django 5.0.1 on 2024-02-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_employee_end_alter_employee_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
