# Generated by Django 5.0.1 on 2024-01-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_customuser_name_remove_customuser_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='John Doe', max_length=30),
        ),
    ]
