# Generated by Django 5.0.1 on 2024-03-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_kpiarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='month',
            field=models.DateTimeField(),
        ),
    ]
