# Generated by Django 5.0.1 on 2024-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calc", "0003_alter_kpi_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi",
            name="end",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="kpi",
            name="start",
            field=models.DateField(null=True),
        ),
    ]
