# Generated by Django 5.0.1 on 2024-02-09 06:19

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
