# Generated by Django 5.0.1 on 2024-04-25 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_kpi_unique_kpi_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpies', to='calc.employee'),
        ),
        migrations.AlterField(
            model_name='kpiarchive',
            name='finished',
            field=models.FloatField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpiarchive',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kpiarchive',
            name='overall',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpiarchive',
            name='start',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpiarchive',
            name='weight',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
    ]
