# Generated by Django 5.0.1 on 2024-01-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_kpi_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
