# Generated by Django 5.0.1 on 2024-02-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_kpi_end_kpi_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='table_number',
            field=models.IntegerField(),
        ),
    ]
