# Generated by Django 5.0.1 on 2024-03-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_alter_kpi_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiarchive',
            name='month',
            field=models.DateTimeField(),
        ),
    ]
