# Generated by Django 5.0.1 on 2024-02-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.TextField(default='default_value'),
        ),
    ]
