# Generated by Django 5.0.1 on 2024-04-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_alter_kpi_employee_alter_kpiarchive_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='premium',
        ),
        migrations.AddField(
            model_name='employee',
            name='premium',
            field=models.TextField(default='Xodim'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='month',
            field=models.DateField(),
        ),
    ]
