# Generated by Django 5.0.1 on 2024-01-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_kpi_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='activity',
            field=models.CharField(default='Нет', max_length=4),
        ),
    ]
