# Generated by Django 5.0.1 on 2024-02-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_employee_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.TextField(default="Bo'linma"),
        ),
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.TextField(default='default_value'),
        ),
    ]
