# Generated by Django 5.0.1 on 2024-04-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_remove_kpi_premium_employee_premium_alter_kpi_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiarchive',
            name='end',
            field=models.DateField(),
        ),
    ]
