# Generated by Django 5.0.1 on 2024-02-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_employee_department_employee_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='table_number',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
