# Generated by Django 5.0.1 on 2024-01-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='premium',
            field=models.TextField(default='default_value'),
        ),
    ]
